Revert "SurfaceFlinger: Allow IdleFallback on start"
This reverts commit e498a405f3dbe5da4d62caec150797f6f26a0d39.

Reason for revert: This CL erroneously passed TreeHugger and has broken builds on q-keystone-qcom-dev.

Error:

FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
Clang SA is not enabled
error: frameworks/native/services/surfaceflinger/tests/unittests/Android.bp:15:1: "libsurfaceflinger_unittest" depends on undefined module "vendor.display.config@1.16"
ninja: build stopped: subcommand failed.
14:05:06 soong bootstrap failed with: exit status 1

Change-Id: I469a200cb595e010e71d311d69b5880df1c6ad97